modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="codecreate"
version="1.0.0"
displayName="Code Create"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Josh, MCreator"

[[dependencies.codecreate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



